"""Sample issues for evaluation harness."""

SAMPLE_ISSUES = [
    {
        "number": 1,
        "title": "Add health check endpoint",
        "body": "Create a /health endpoint that returns {status: 'ok'} with 200 status code.",
        "expected_files": ["app/main.py"],
        "complexity": "low",
    },
    {
        "number": 2,
        "title": "Add pagination to notes list",
        "body": "Add query parameters 'limit' and 'offset' to GET /api/notes endpoint.",
        "expected_files": ["app/main.py"],
        "complexity": "medium",
    },
    {
        "number": 3,
        "title": "Add note search functionality",
        "body": "Add GET /api/notes/search?q=query endpoint to search notes by title or content.",
        "expected_files": ["app/main.py"],
        "complexity": "medium",
    },
    {
        "number": 4,
        "title": "Add created_at filter",
        "body": "Add query parameters 'after' and 'before' to filter notes by creation date.",
        "expected_files": ["app/main.py"],
        "complexity": "medium",
    },
    {
        "number": 5,
        "title": "Add input validation",
        "body": "Validate that title is not empty and content is at least 10 characters.",
        "expected_files": ["app/main.py"],
        "complexity": "low",
    },
    {
        "number": 6,
        "title": "Add note tags",
        "body": "Add a 'tags' field (list of strings) to notes. Update create, update, and list endpoints.",
        "expected_files": ["app/main.py"],
        "complexity": "high",
    },
    {
        "number": 7,
        "title": "Add rate limiting",
        "body": "Implement rate limiting: max 100 requests per minute per IP.",
        "expected_files": ["app/main.py"],
        "complexity": "high",
    },
    {
        "number": 8,
        "title": "Add note archival",
        "body": "Add 'archived' boolean field. Add POST /api/notes/{id}/archive endpoint.",
        "expected_files": ["app/main.py"],
        "complexity": "medium",
    },
    {
        "number": 9,
        "title": "Add bulk delete",
        "body": "Add POST /api/notes/bulk-delete endpoint that accepts list of note IDs.",
        "expected_files": ["app/main.py"],
        "complexity": "medium",
    },
    {
        "number": 10,
        "title": "Add version endpoint",
        "body": "Add GET /api/version endpoint that returns the API version.",
        "expected_files": ["app/main.py"],
        "complexity": "low",
    },
    {
        "number": 11,
        "title": "Add note statistics",
        "body": "Add GET /api/stats endpoint returning total notes count and average content length.",
        "expected_files": ["app/main.py"],
        "complexity": "medium",
    },
    {
        "number": 12,
        "title": "Add CORS support",
        "body": "Enable CORS middleware for frontend integration.",
        "expected_files": ["app/main.py"],
        "complexity": "low",
    },
    {
        "number": 13,
        "title": "Add note duplication check",
        "body": "Prevent creating notes with identical title and content.",
        "expected_files": ["app/main.py"],
        "complexity": "medium",
    },
    {
        "number": 14,
        "title": "Add sorting options",
        "body": "Add 'sort_by' query param to /api/notes (created_at, updated_at, title).",
        "expected_files": ["app/main.py"],
        "complexity": "medium",
    },
    {
        "number": 15,
        "title": "Add note sharing",
        "body": "Add 'shared' boolean and GET /api/notes/shared endpoint for public notes.",
        "expected_files": ["app/main.py"],
        "complexity": "medium",
    },
    {
        "number": 16,
        "title": "Add note export",
        "body": "Add GET /api/notes/export endpoint that returns all notes as JSON file.",
        "expected_files": ["app/main.py"],
        "complexity": "medium",
    },
    {
        "number": 17,
        "title": "Add character count",
        "body": "Add 'char_count' field to Note model calculated from content length.",
        "expected_files": ["app/main.py"],
        "complexity": "low",
    },
    {
        "number": 18,
        "title": "Add error handling",
        "body": "Add global exception handler that returns consistent error format.",
        "expected_files": ["app/main.py"],
        "complexity": "medium",
    },
    {
        "number": 19,
        "title": "Add note favorites",
        "body": "Add 'favorite' boolean field and GET /api/notes/favorites endpoint.",
        "expected_files": ["app/main.py"],
        "complexity": "medium",
    },
    {
        "number": 20,
        "title": "Add request logging",
        "body": "Add middleware to log all API requests with timestamp and endpoint.",
        "expected_files": ["app/main.py"],
        "complexity": "medium",
    },
]
